version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: sqlite:////code/app.db
    command: flask run --host=0.0.0.0
